# Generated by Django 3.2.5 on 2021-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tuples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalRate', models.FloatField()),
                ('arrivalCV', models.FloatField()),
                ('serviceRate', models.FloatField()),
                ('serviceTimeCV', models.FloatField()),
                ('speed', models.FloatField()),
                ('predicted', models.IntegerField()),
            ],
        ),
    ]
