# Generated by Django 3.2.5 on 2021-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuples',
            name='title',
            field=models.CharField(default='123', max_length=30),
        ),
    ]
