# Generated by Django 3.2.5 on 2021-07-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_tuples_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tuples',
            new_name='tuple',
        ),
    ]
